// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: services/rpc/upload/desc/upload.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          []byte                 `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`                 // 文件二进制
	FileName      string                 `protobuf:"bytes,2,opt,name=fileName,proto3" json:"fileName,omitempty"`         // 原始文件名
	FileSize      int64                  `protobuf:"varint,3,opt,name=fileSize,proto3" json:"fileSize,omitempty"`        // 文件大小
	FileType      string                 `protobuf:"bytes,4,opt,name=fileType,proto3" json:"fileType,omitempty"`         // 文件类型(image/png)
	UploadUserID  string                 `protobuf:"bytes,5,opt,name=uploadUserID,proto3" json:"uploadUserID,omitempty"` // 上传者用户ID（权限控制核心）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadReq) Reset() {
	*x = UploadReq{}
	mi := &file_services_rpc_upload_desc_upload_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadReq) ProtoMessage() {}

func (x *UploadReq) ProtoReflect() protoreflect.Message {
	mi := &file_services_rpc_upload_desc_upload_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadReq.ProtoReflect.Descriptor instead.
func (*UploadReq) Descriptor() ([]byte, []int) {
	return file_services_rpc_upload_desc_upload_proto_rawDescGZIP(), []int{0}
}

func (x *UploadReq) GetFile() []byte {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *UploadReq) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *UploadReq) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *UploadReq) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

func (x *UploadReq) GetUploadUserID() string {
	if x != nil {
		return x.UploadUserID
	}
	return ""
}

type UploadResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	FilePath      string                 `protobuf:"bytes,2,opt,name=filePath,proto3" json:"filePath,omitempty"` // OSS访问URL
	FileName      string                 `protobuf:"bytes,3,opt,name=fileName,proto3" json:"fileName,omitempty"`
	FileSize      int64                  `protobuf:"varint,4,opt,name=fileSize,proto3" json:"fileSize,omitempty"`
	FileType      string                 `protobuf:"bytes,5,opt,name=fileType,proto3" json:"fileType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadResp) Reset() {
	*x = UploadResp{}
	mi := &file_services_rpc_upload_desc_upload_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadResp) ProtoMessage() {}

func (x *UploadResp) ProtoReflect() protoreflect.Message {
	mi := &file_services_rpc_upload_desc_upload_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadResp.ProtoReflect.Descriptor instead.
func (*UploadResp) Descriptor() ([]byte, []int) {
	return file_services_rpc_upload_desc_upload_proto_rawDescGZIP(), []int{1}
}

func (x *UploadResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *UploadResp) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *UploadResp) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *UploadResp) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *UploadResp) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

var File_services_rpc_upload_desc_upload_proto protoreflect.FileDescriptor

const file_services_rpc_upload_desc_upload_proto_rawDesc = "" +
	"\n" +
	"%services/rpc/upload/desc/upload.proto\x12\x06upload\"\x97\x01\n" +
	"\tUploadReq\x12\x12\n" +
	"\x04file\x18\x01 \x01(\fR\x04file\x12\x1a\n" +
	"\bfileName\x18\x02 \x01(\tR\bfileName\x12\x1a\n" +
	"\bfileSize\x18\x03 \x01(\x03R\bfileSize\x12\x1a\n" +
	"\bfileType\x18\x04 \x01(\tR\bfileType\x12\"\n" +
	"\fuploadUserID\x18\x05 \x01(\tR\fuploadUserID\"\x8e\x01\n" +
	"\n" +
	"UploadResp\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\x12\x1a\n" +
	"\bfilePath\x18\x02 \x01(\tR\bfilePath\x12\x1a\n" +
	"\bfileName\x18\x03 \x01(\tR\bfileName\x12\x1a\n" +
	"\bfileSize\x18\x04 \x01(\x03R\bfileSize\x12\x1a\n" +
	"\bfileType\x18\x05 \x01(\tR\bfileType29\n" +
	"\x06Upload\x12/\n" +
	"\x06Upload\x12\x11.upload.UploadReq\x1a\x12.upload.UploadRespB\x06Z\x04./pbb\x06proto3"

var (
	file_services_rpc_upload_desc_upload_proto_rawDescOnce sync.Once
	file_services_rpc_upload_desc_upload_proto_rawDescData []byte
)

func file_services_rpc_upload_desc_upload_proto_rawDescGZIP() []byte {
	file_services_rpc_upload_desc_upload_proto_rawDescOnce.Do(func() {
		file_services_rpc_upload_desc_upload_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_rpc_upload_desc_upload_proto_rawDesc), len(file_services_rpc_upload_desc_upload_proto_rawDesc)))
	})
	return file_services_rpc_upload_desc_upload_proto_rawDescData
}

var file_services_rpc_upload_desc_upload_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_services_rpc_upload_desc_upload_proto_goTypes = []any{
	(*UploadReq)(nil),  // 0: upload.UploadReq
	(*UploadResp)(nil), // 1: upload.UploadResp
}
var file_services_rpc_upload_desc_upload_proto_depIdxs = []int32{
	0, // 0: upload.Upload.Upload:input_type -> upload.UploadReq
	1, // 1: upload.Upload.Upload:output_type -> upload.UploadResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_services_rpc_upload_desc_upload_proto_init() }
func file_services_rpc_upload_desc_upload_proto_init() {
	if File_services_rpc_upload_desc_upload_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_rpc_upload_desc_upload_proto_rawDesc), len(file_services_rpc_upload_desc_upload_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_rpc_upload_desc_upload_proto_goTypes,
		DependencyIndexes: file_services_rpc_upload_desc_upload_proto_depIdxs,
		MessageInfos:      file_services_rpc_upload_desc_upload_proto_msgTypes,
	}.Build()
	File_services_rpc_upload_desc_upload_proto = out.File
	file_services_rpc_upload_desc_upload_proto_goTypes = nil
	file_services_rpc_upload_desc_upload_proto_depIdxs = nil
}
