// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: auth.proto

package userservice

import (
	"context"

	"gomicrox/services/rpc/auth/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	DeleteUserReq         = pb.DeleteUserReq
	DeleteUserResp        = pb.DeleteUserResp
	EmailLoginReq         = pb.EmailLoginReq
	EmailRegisterReq      = pb.EmailRegisterReq
	GetUserDetailReq      = pb.GetUserDetailReq
	GetUserDetailResp     = pb.GetUserDetailResp
	GetUserInfoReq        = pb.GetUserInfoReq
	GetUserInfoResp       = pb.GetUserInfoResp
	GetUserProfileReq     = pb.GetUserProfileReq
	GetUserProfileResp    = pb.GetUserProfileResp
	ListUsersReq          = pb.ListUsersReq
	ListUsersResp         = pb.ListUsersResp
	LoginByCodeReq        = pb.LoginByCodeReq
	LoginByCodeResp       = pb.LoginByCodeResp
	LoginResp             = pb.LoginResp
	RegisterResp          = pb.RegisterResp
	SendCodeReq           = pb.SendCodeReq
	SendCodeResp          = pb.SendCodeResp
	UpdateUserProfileReq  = pb.UpdateUserProfileReq
	UpdateUserProfileResp = pb.UpdateUserProfileResp
	UpdateUserStatusReq   = pb.UpdateUserStatusReq
	UpdateUserStatusResp  = pb.UpdateUserStatusResp
	User                  = pb.User
	UserListItem          = pb.UserListItem
	UsernameLoginReq      = pb.UsernameLoginReq
	ValidateTokenReq      = pb.ValidateTokenReq
	ValidateTokenResp     = pb.ValidateTokenResp

	UserService interface {
		GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoResp, error)
		GetUserProfile(ctx context.Context, in *GetUserProfileReq, opts ...grpc.CallOption) (*GetUserProfileResp, error)
		UpdateUserProfile(ctx context.Context, in *UpdateUserProfileReq, opts ...grpc.CallOption) (*UpdateUserProfileResp, error)
		// 管理后台接口
		ListUsers(ctx context.Context, in *ListUsersReq, opts ...grpc.CallOption) (*ListUsersResp, error)
		GetUserDetail(ctx context.Context, in *GetUserDetailReq, opts ...grpc.CallOption) (*GetUserDetailResp, error)
		UpdateUserStatus(ctx context.Context, in *UpdateUserStatusReq, opts ...grpc.CallOption) (*UpdateUserStatusResp, error)
		DeleteUser(ctx context.Context, in *DeleteUserReq, opts ...grpc.CallOption) (*DeleteUserResp, error)
	}

	defaultUserService struct {
		cli zrpc.Client
	}
)

func NewUserService(cli zrpc.Client) UserService {
	return &defaultUserService{
		cli: cli,
	}
}

func (m *defaultUserService) GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoResp, error) {
	client := pb.NewUserServiceClient(m.cli.Conn())
	return client.GetUserInfo(ctx, in, opts...)
}

func (m *defaultUserService) GetUserProfile(ctx context.Context, in *GetUserProfileReq, opts ...grpc.CallOption) (*GetUserProfileResp, error) {
	client := pb.NewUserServiceClient(m.cli.Conn())
	return client.GetUserProfile(ctx, in, opts...)
}

func (m *defaultUserService) UpdateUserProfile(ctx context.Context, in *UpdateUserProfileReq, opts ...grpc.CallOption) (*UpdateUserProfileResp, error) {
	client := pb.NewUserServiceClient(m.cli.Conn())
	return client.UpdateUserProfile(ctx, in, opts...)
}

// 管理后台接口
func (m *defaultUserService) ListUsers(ctx context.Context, in *ListUsersReq, opts ...grpc.CallOption) (*ListUsersResp, error) {
	client := pb.NewUserServiceClient(m.cli.Conn())
	return client.ListUsers(ctx, in, opts...)
}

func (m *defaultUserService) GetUserDetail(ctx context.Context, in *GetUserDetailReq, opts ...grpc.CallOption) (*GetUserDetailResp, error) {
	client := pb.NewUserServiceClient(m.cli.Conn())
	return client.GetUserDetail(ctx, in, opts...)
}

func (m *defaultUserService) UpdateUserStatus(ctx context.Context, in *UpdateUserStatusReq, opts ...grpc.CallOption) (*UpdateUserStatusResp, error) {
	client := pb.NewUserServiceClient(m.cli.Conn())
	return client.UpdateUserStatus(ctx, in, opts...)
}

func (m *defaultUserService) DeleteUser(ctx context.Context, in *DeleteUserReq, opts ...grpc.CallOption) (*DeleteUserResp, error) {
	client := pb.NewUserServiceClient(m.cli.Conn())
	return client.DeleteUser(ctx, in, opts...)
}
