// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: upload.proto

package upload

import (
	"context"

	"gomicrox/services/rpc/upload/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	UploadReq  = pb.UploadReq
	UploadResp = pb.UploadResp

	Upload interface {
		Upload(ctx context.Context, in *UploadReq, opts ...grpc.CallOption) (*UploadResp, error)
	}

	defaultUpload struct {
		cli zrpc.Client
	}
)

func NewUpload(cli zrpc.Client) Upload {
	return &defaultUpload{
		cli: cli,
	}
}

func (m *defaultUpload) Upload(ctx context.Context, in *UploadReq, opts ...grpc.CallOption) (*UploadResp, error) {
	client := pb.NewUploadClient(m.cli.Conn())
	return client.Upload(ctx, in, opts...)
}
