// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: auth.proto

package server

import (
	"context"

	"gomicrox/services/rpc/auth/internal/logic/authservice"
	"gomicrox/services/rpc/auth/internal/svc"
	"gomicrox/services/rpc/auth/pb"
)

type AuthServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedAuthServiceServer
}

func NewAuthServiceServer(svcCtx *svc.ServiceContext) *AuthServiceServer {
	return &AuthServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *AuthServiceServer) UsernameLogin(ctx context.Context, in *pb.UsernameLoginReq) (*pb.LoginResp, error) {
	l := authservicelogic.NewUsernameLoginLogic(ctx, s.svcCtx)
	return l.UsernameLogin(in)
}

func (s *AuthServiceServer) EmailLogin(ctx context.Context, in *pb.EmailLoginReq) (*pb.LoginResp, error) {
	l := authservicelogic.NewEmailLoginLogic(ctx, s.svcCtx)
	return l.EmailLogin(in)
}

func (s *AuthServiceServer) EmailRegister(ctx context.Context, in *pb.EmailRegisterReq) (*pb.RegisterResp, error) {
	l := authservicelogic.NewEmailRegisterLogic(ctx, s.svcCtx)
	return l.EmailRegister(in)
}

func (s *AuthServiceServer) ValidateToken(ctx context.Context, in *pb.ValidateTokenReq) (*pb.ValidateTokenResp, error) {
	l := authservicelogic.NewValidateTokenLogic(ctx, s.svcCtx)
	return l.ValidateToken(in)
}

func (s *AuthServiceServer) SendCode(ctx context.Context, in *pb.SendCodeReq) (*pb.SendCodeResp, error) {
	l := authservicelogic.NewSendCodeLogic(ctx, s.svcCtx)
	return l.SendCode(in)
}

func (s *AuthServiceServer) LoginByCode(ctx context.Context, in *pb.LoginByCodeReq) (*pb.LoginByCodeResp, error) {
	l := authservicelogic.NewLoginByCodeLogic(ctx, s.svcCtx)
	return l.LoginByCode(in)
}
