// Code generated by goctl. DO NOT EDIT.

package types

type UploadReq struct {
}

type UploadResp struct {
	Msg  string     `json:"msg"`
	Data UploadData `json:"data"`
}

type UploadData struct {
	FileName string `json:"fileName"`
	FilePath string `json:"filePath"`
	FileSize int64  `json:"fileSize"`
	FileType string `json:"fileType"`
}
