// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: auth.proto

package server

import (
	"context"

	"gomicrox/services/rpc/auth/internal/logic/userservice"
	"gomicrox/services/rpc/auth/internal/svc"
	"gomicrox/services/rpc/auth/pb"
)

type UserServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedUserServiceServer
}

func NewUserServiceServer(svcCtx *svc.ServiceContext) *UserServiceServer {
	return &UserServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServiceServer) GetUserInfo(ctx context.Context, in *pb.GetUserInfoReq) (*pb.GetUserInfoResp, error) {
	l := userservicelogic.NewGetUserInfoLogic(ctx, s.svcCtx)
	return l.GetUserInfo(in)
}

func (s *UserServiceServer) GetUserProfile(ctx context.Context, in *pb.GetUserProfileReq) (*pb.GetUserProfileResp, error) {
	l := userservicelogic.NewGetUserProfileLogic(ctx, s.svcCtx)
	return l.GetUserProfile(in)
}

func (s *UserServiceServer) UpdateUserProfile(ctx context.Context, in *pb.UpdateUserProfileReq) (*pb.UpdateUserProfileResp, error) {
	l := userservicelogic.NewUpdateUserProfileLogic(ctx, s.svcCtx)
	return l.UpdateUserProfile(in)
}

// 管理后台接口
func (s *UserServiceServer) ListUsers(ctx context.Context, in *pb.ListUsersReq) (*pb.ListUsersResp, error) {
	l := userservicelogic.NewListUsersLogic(ctx, s.svcCtx)
	return l.ListUsers(in)
}

func (s *UserServiceServer) GetUserDetail(ctx context.Context, in *pb.GetUserDetailReq) (*pb.GetUserDetailResp, error) {
	l := userservicelogic.NewGetUserDetailLogic(ctx, s.svcCtx)
	return l.GetUserDetail(in)
}

func (s *UserServiceServer) UpdateUserStatus(ctx context.Context, in *pb.UpdateUserStatusReq) (*pb.UpdateUserStatusResp, error) {
	l := userservicelogic.NewUpdateUserStatusLogic(ctx, s.svcCtx)
	return l.UpdateUserStatus(in)
}

func (s *UserServiceServer) DeleteUser(ctx context.Context, in *pb.DeleteUserReq) (*pb.DeleteUserResp, error) {
	l := userservicelogic.NewDeleteUserLogic(ctx, s.svcCtx)
	return l.DeleteUser(in)
}
