// Code generated by goctl. DO NOT EDIT.

package auth

import (
	"gomicrox/services/rpc/auth/client/authservice"
	"gomicrox/services/rpc/auth/client/userservice"
	"gomicrox/services/rpc/auth/pb"

	"github.com/zeromicro/go-zero/zrpc"
)

type (
	EmailLoginReq         = pb.EmailLoginReq
	EmailRegisterReq      = pb.EmailRegisterReq
	GetUserInfoReq        = pb.GetUserInfoReq
	GetUserInfoResp       = pb.GetUserInfoResp
	GetUserProfileReq     = pb.GetUserProfileReq
	GetUserProfileResp    = pb.GetUserProfileResp
	LoginByCodeReq        = pb.LoginByCodeReq
	LoginByCodeResp       = pb.LoginByCodeResp
	LoginResp             = pb.LoginResp
	RegisterResp          = pb.RegisterResp
	SendCodeReq           = pb.SendCodeReq
	SendCodeResp          = pb.SendCodeResp
	UpdateUserProfileReq  = pb.UpdateUserProfileReq
	UpdateUserProfileResp = pb.UpdateUserProfileResp
	User                  = pb.User
	UsernameLoginReq      = pb.UsernameLoginReq
	ValidateTokenReq      = pb.ValidateTokenReq
	ValidateTokenResp     = pb.ValidateTokenResp

	Auth interface {
		authservice.AuthService
		userservice.UserService
	}

	defaultAuth struct {
		authservice.AuthService
		userservice.UserService
	}
)

func NewAuth(cli zrpc.Client) Auth {
	return &defaultAuth{
		AuthService: authservice.NewAuthService(cli),
		UserService: userservice.NewUserService(cli),
	}
}
