// Code generated by goctl. Not to edit.

package types

type UserListReq struct {
	Page     int `json:"page" form:"page,default=1"`
	PageSize int `json:"page_size" form:"page_size,default=10"`
	Status   int `json:"status" form:"status,default=0"`
	Role     int `json:"role" form:"role,default=0"`
}

type UserItem struct {
	UserId    string `json:"user_id"`
	Username  string `json:"username"`
	Email     string `json:"email"`
	Phone     string `json:"phone"`
	Role      int64  `json:"role"`
	Status    int64  `json:"status"`
	Avatar    string `json:"avatar"`
	Remark    string `json:"remark"`
	CreatedAt string `json:"created_at"`
}

type UserListResp struct {
	List     []UserItem `json:"list"`
	Total    int64      `json:"total"`
	Page     int        `json:"page"`
	PageSize int        `json:"page_size"`
}

type GetUserDetailReq struct {
	UserId string `json:"user_id" path:"user_id"`
}

type GetUserDetailResp struct {
	UserId    string `json:"user_id"`
	Username  string `json:"username"`
	Email     string `json:"email"`
	Phone     string `json:"phone"`
	Role      int64  `json:"role"`
	Status    int64  `json:"status"`
	Avatar    string `json:"avatar"`
	Remark    string `json:"remark"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type UpdateUserStatusReq struct {
	UserId string `json:"user_id"`
	Status int64  `json:"status" validate:"required,oneof=1 2 3 4"`
}

type UpdateUserStatusResp struct {
	Success bool `json:"success"`
}

type DeleteUserReq struct {
	UserId string `json:"user_id" path:"user_id"`
}

type DeleteUserResp struct {
	Success bool `json:"success"`
}
