// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: upload.proto

package server

import (
	"context"

	"gomicrox/services/rpc/upload/internal/logic"
	"gomicrox/services/rpc/upload/internal/svc"
	"gomicrox/services/rpc/upload/pb"
)

type UploadServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedUploadServer
}

func NewUploadServer(svcCtx *svc.ServiceContext) *UploadServer {
	return &UploadServer{
		svcCtx: svcCtx,
	}
}

func (s *UploadServer) Upload(ctx context.Context, in *pb.UploadReq) (*pb.UploadResp, error) {
	l := logic.NewUploadLogic(ctx, s.svcCtx)
	return l.Upload(in)
}
