// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: services/rpc/auth/desc/auth.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 用户基础信息
type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Avatar        string                 `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Phone         string                 `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	Role          int32                  `protobuf:"varint,6,opt,name=role,proto3" json:"role,omitempty"`
	Status        int32                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_services_rpc_auth_desc_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_services_rpc_auth_desc_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_services_rpc_auth_desc_auth_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *User) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *User) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

func (x *User) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// 用户名登录
type UsernameLoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsernameLoginReq) Reset() {
	*x = UsernameLoginReq{}
	mi := &file_services_rpc_auth_desc_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsernameLoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsernameLoginReq) ProtoMessage() {}

func (x *UsernameLoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_services_rpc_auth_desc_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsernameLoginReq.ProtoReflect.Descriptor instead.
func (*UsernameLoginReq) Descriptor() ([]byte, []int) {
	return file_services_rpc_auth_desc_auth_proto_rawDescGZIP(), []int{1}
}

func (x *UsernameLoginReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UsernameLoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// 邮箱登录
type EmailLoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailLoginReq) Reset() {
	*x = EmailLoginReq{}
	mi := &file_services_rpc_auth_desc_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailLoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailLoginReq) ProtoMessage() {}

func (x *EmailLoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_services_rpc_auth_desc_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailLoginReq.ProtoReflect.Descriptor instead.
func (*EmailLoginReq) Descriptor() ([]byte, []int) {
	return file_services_rpc_auth_desc_auth_proto_rawDescGZIP(), []int{2}
}

func (x *EmailLoginReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *EmailLoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// 登录响应
type LoginResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          int32                  `protobuf:"varint,3,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResp) Reset() {
	*x = LoginResp{}
	mi := &file_services_rpc_auth_desc_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResp) ProtoMessage() {}

func (x *LoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_services_rpc_auth_desc_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResp.ProtoReflect.Descriptor instead.
func (*LoginResp) Descriptor() ([]byte, []int) {
	return file_services_rpc_auth_desc_auth_proto_rawDescGZIP(), []int{3}
}

func (x *LoginResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginResp) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LoginResp) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

// 邮箱注册
type EmailRegisterReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Code          string                 `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailRegisterReq) Reset() {
	*x = EmailRegisterReq{}
	mi := &file_services_rpc_auth_desc_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailRegisterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailRegisterReq) ProtoMessage() {}

func (x *EmailRegisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_services_rpc_auth_desc_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailRegisterReq.ProtoReflect.Descriptor instead.
func (*EmailRegisterReq) Descriptor() ([]byte, []int) {
	return file_services_rpc_auth_desc_auth_proto_rawDescGZIP(), []int{4}
}

func (x *EmailRegisterReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *EmailRegisterReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *EmailRegisterReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *EmailRegisterReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

// 注册响应
type RegisterResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResp) Reset() {
	*x = RegisterResp{}
	mi := &file_services_rpc_auth_desc_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResp) ProtoMessage() {}

func (x *RegisterResp) ProtoReflect() protoreflect.Message {
	mi := &file_services_rpc_auth_desc_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResp.ProtoReflect.Descriptor instead.
func (*RegisterResp) Descriptor() ([]byte, []int) {
	return file_services_rpc_auth_desc_auth_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 验证 token
type ValidateTokenReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenReq) Reset() {
	*x = ValidateTokenReq{}
	mi := &file_services_rpc_auth_desc_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenReq) ProtoMessage() {}

func (x *ValidateTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_services_rpc_auth_desc_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenReq.ProtoReflect.Descriptor instead.
func (*ValidateTokenReq) Descriptor() ([]byte, []int) {
	return file_services_rpc_auth_desc_auth_proto_rawDescGZIP(), []int{6}
}

func (x *ValidateTokenReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ValidateTokenResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenResp) Reset() {
	*x = ValidateTokenResp{}
	mi := &file_services_rpc_auth_desc_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenResp) ProtoMessage() {}

func (x *ValidateTokenResp) ProtoReflect() protoreflect.Message {
	mi := &file_services_rpc_auth_desc_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenResp.ProtoReflect.Descriptor instead.
func (*ValidateTokenResp) Descriptor() ([]byte, []int) {
	return file_services_rpc_auth_desc_auth_proto_rawDescGZIP(), []int{7}
}

func (x *ValidateTokenResp) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

// 发送验证码
type SendCodeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendCodeReq) Reset() {
	*x = SendCodeReq{}
	mi := &file_services_rpc_auth_desc_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendCodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendCodeReq) ProtoMessage() {}

func (x *SendCodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_services_rpc_auth_desc_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendCodeReq.ProtoReflect.Descriptor instead.
func (*SendCodeReq) Descriptor() ([]byte, []int) {
	return file_services_rpc_auth_desc_auth_proto_rawDescGZIP(), []int{8}
}

func (x *SendCodeReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type SendCodeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendCodeResp) Reset() {
	*x = SendCodeResp{}
	mi := &file_services_rpc_auth_desc_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendCodeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendCodeResp) ProtoMessage() {}

func (x *SendCodeResp) ProtoReflect() protoreflect.Message {
	mi := &file_services_rpc_auth_desc_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendCodeResp.ProtoReflect.Descriptor instead.
func (*SendCodeResp) Descriptor() ([]byte, []int) {
	return file_services_rpc_auth_desc_auth_proto_rawDescGZIP(), []int{9}
}

func (x *SendCodeResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 验证码登录
type LoginByCodeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginByCodeReq) Reset() {
	*x = LoginByCodeReq{}
	mi := &file_services_rpc_auth_desc_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginByCodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginByCodeReq) ProtoMessage() {}

func (x *LoginByCodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_services_rpc_auth_desc_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginByCodeReq.ProtoReflect.Descriptor instead.
func (*LoginByCodeReq) Descriptor() ([]byte, []int) {
	return file_services_rpc_auth_desc_auth_proto_rawDescGZIP(), []int{10}
}

func (x *LoginByCodeReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginByCodeReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type LoginByCodeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Role          int32                  `protobuf:"varint,3,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginByCodeResp) Reset() {
	*x = LoginByCodeResp{}
	mi := &file_services_rpc_auth_desc_auth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginByCodeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginByCodeResp) ProtoMessage() {}

func (x *LoginByCodeResp) ProtoReflect() protoreflect.Message {
	mi := &file_services_rpc_auth_desc_auth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginByCodeResp.ProtoReflect.Descriptor instead.
func (*LoginByCodeResp) Descriptor() ([]byte, []int) {
	return file_services_rpc_auth_desc_auth_proto_rawDescGZIP(), []int{11}
}

func (x *LoginByCodeResp) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LoginByCodeResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginByCodeResp) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

// 获取用户信息
type GetUserInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoReq) Reset() {
	*x = GetUserInfoReq{}
	mi := &file_services_rpc_auth_desc_auth_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoReq) ProtoMessage() {}

func (x *GetUserInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_services_rpc_auth_desc_auth_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoReq.ProtoReflect.Descriptor instead.
func (*GetUserInfoReq) Descriptor() ([]byte, []int) {
	return file_services_rpc_auth_desc_auth_proto_rawDescGZIP(), []int{12}
}

func (x *GetUserInfoReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Avatar        string                 `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Phone         string                 `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoResp) Reset() {
	*x = GetUserInfoResp{}
	mi := &file_services_rpc_auth_desc_auth_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoResp) ProtoMessage() {}

func (x *GetUserInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_services_rpc_auth_desc_auth_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoResp.ProtoReflect.Descriptor instead.
func (*GetUserInfoResp) Descriptor() ([]byte, []int) {
	return file_services_rpc_auth_desc_auth_proto_rawDescGZIP(), []int{13}
}

func (x *GetUserInfoResp) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserInfoResp) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetUserInfoResp) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GetUserInfoResp) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *GetUserInfoResp) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

// 获取个人资料
type GetUserProfileReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserProfileReq) Reset() {
	*x = GetUserProfileReq{}
	mi := &file_services_rpc_auth_desc_auth_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProfileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProfileReq) ProtoMessage() {}

func (x *GetUserProfileReq) ProtoReflect() protoreflect.Message {
	mi := &file_services_rpc_auth_desc_auth_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProfileReq.ProtoReflect.Descriptor instead.
func (*GetUserProfileReq) Descriptor() ([]byte, []int) {
	return file_services_rpc_auth_desc_auth_proto_rawDescGZIP(), []int{14}
}

func (x *GetUserProfileReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserProfileResp struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RealName         string                 `protobuf:"bytes,2,opt,name=real_name,json=realName,proto3" json:"real_name,omitempty"`
	School           string                 `protobuf:"bytes,3,opt,name=school,proto3" json:"school,omitempty"`
	Major            string                 `protobuf:"bytes,4,opt,name=major,proto3" json:"major,omitempty"`
	Grade            string                 `protobuf:"bytes,5,opt,name=grade,proto3" json:"grade,omitempty"`
	Gender           int32                  `protobuf:"varint,6,opt,name=gender,proto3" json:"gender,omitempty"`
	ExpectedCity     string                 `protobuf:"bytes,7,opt,name=expected_city,json=expectedCity,proto3" json:"expected_city,omitempty"`
	ExpectedPosition string                 `protobuf:"bytes,8,opt,name=expected_position,json=expectedPosition,proto3" json:"expected_position,omitempty"`
	SelfIntroduction string                 `protobuf:"bytes,9,opt,name=self_introduction,json=selfIntroduction,proto3" json:"self_introduction,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetUserProfileResp) Reset() {
	*x = GetUserProfileResp{}
	mi := &file_services_rpc_auth_desc_auth_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProfileResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProfileResp) ProtoMessage() {}

func (x *GetUserProfileResp) ProtoReflect() protoreflect.Message {
	mi := &file_services_rpc_auth_desc_auth_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProfileResp.ProtoReflect.Descriptor instead.
func (*GetUserProfileResp) Descriptor() ([]byte, []int) {
	return file_services_rpc_auth_desc_auth_proto_rawDescGZIP(), []int{15}
}

func (x *GetUserProfileResp) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserProfileResp) GetRealName() string {
	if x != nil {
		return x.RealName
	}
	return ""
}

func (x *GetUserProfileResp) GetSchool() string {
	if x != nil {
		return x.School
	}
	return ""
}

func (x *GetUserProfileResp) GetMajor() string {
	if x != nil {
		return x.Major
	}
	return ""
}

func (x *GetUserProfileResp) GetGrade() string {
	if x != nil {
		return x.Grade
	}
	return ""
}

func (x *GetUserProfileResp) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *GetUserProfileResp) GetExpectedCity() string {
	if x != nil {
		return x.ExpectedCity
	}
	return ""
}

func (x *GetUserProfileResp) GetExpectedPosition() string {
	if x != nil {
		return x.ExpectedPosition
	}
	return ""
}

func (x *GetUserProfileResp) GetSelfIntroduction() string {
	if x != nil {
		return x.SelfIntroduction
	}
	return ""
}

// 更新个人资料
type UpdateUserProfileReq struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RealName         string                 `protobuf:"bytes,2,opt,name=real_name,json=realName,proto3" json:"real_name,omitempty"`
	School           string                 `protobuf:"bytes,3,opt,name=school,proto3" json:"school,omitempty"`
	Major            string                 `protobuf:"bytes,4,opt,name=major,proto3" json:"major,omitempty"`
	Grade            string                 `protobuf:"bytes,5,opt,name=grade,proto3" json:"grade,omitempty"`
	Gender           int32                  `protobuf:"varint,6,opt,name=gender,proto3" json:"gender,omitempty"`
	ExpectedCity     string                 `protobuf:"bytes,7,opt,name=expected_city,json=expectedCity,proto3" json:"expected_city,omitempty"`
	ExpectedPosition string                 `protobuf:"bytes,8,opt,name=expected_position,json=expectedPosition,proto3" json:"expected_position,omitempty"`
	SelfIntroduction string                 `protobuf:"bytes,9,opt,name=self_introduction,json=selfIntroduction,proto3" json:"self_introduction,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateUserProfileReq) Reset() {
	*x = UpdateUserProfileReq{}
	mi := &file_services_rpc_auth_desc_auth_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserProfileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserProfileReq) ProtoMessage() {}

func (x *UpdateUserProfileReq) ProtoReflect() protoreflect.Message {
	mi := &file_services_rpc_auth_desc_auth_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserProfileReq.ProtoReflect.Descriptor instead.
func (*UpdateUserProfileReq) Descriptor() ([]byte, []int) {
	return file_services_rpc_auth_desc_auth_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateUserProfileReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateUserProfileReq) GetRealName() string {
	if x != nil {
		return x.RealName
	}
	return ""
}

func (x *UpdateUserProfileReq) GetSchool() string {
	if x != nil {
		return x.School
	}
	return ""
}

func (x *UpdateUserProfileReq) GetMajor() string {
	if x != nil {
		return x.Major
	}
	return ""
}

func (x *UpdateUserProfileReq) GetGrade() string {
	if x != nil {
		return x.Grade
	}
	return ""
}

func (x *UpdateUserProfileReq) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *UpdateUserProfileReq) GetExpectedCity() string {
	if x != nil {
		return x.ExpectedCity
	}
	return ""
}

func (x *UpdateUserProfileReq) GetExpectedPosition() string {
	if x != nil {
		return x.ExpectedPosition
	}
	return ""
}

func (x *UpdateUserProfileReq) GetSelfIntroduction() string {
	if x != nil {
		return x.SelfIntroduction
	}
	return ""
}

type UpdateUserProfileResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserProfileResp) Reset() {
	*x = UpdateUserProfileResp{}
	mi := &file_services_rpc_auth_desc_auth_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserProfileResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserProfileResp) ProtoMessage() {}

func (x *UpdateUserProfileResp) ProtoReflect() protoreflect.Message {
	mi := &file_services_rpc_auth_desc_auth_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserProfileResp.ProtoReflect.Descriptor instead.
func (*UpdateUserProfileResp) Descriptor() ([]byte, []int) {
	return file_services_rpc_auth_desc_auth_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateUserProfileResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 用户列表请求
type ListUsersReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Status        int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	Role          int32                  `protobuf:"varint,4,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersReq) Reset() {
	*x = ListUsersReq{}
	mi := &file_services_rpc_auth_desc_auth_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersReq) ProtoMessage() {}

func (x *ListUsersReq) ProtoReflect() protoreflect.Message {
	mi := &file_services_rpc_auth_desc_auth_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersReq.ProtoReflect.Descriptor instead.
func (*ListUsersReq) Descriptor() ([]byte, []int) {
	return file_services_rpc_auth_desc_auth_proto_rawDescGZIP(), []int{18}
}

func (x *ListUsersReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListUsersReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListUsersReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ListUsersReq) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

// 用户列表项
type UserListItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Role          int32                  `protobuf:"varint,5,opt,name=role,proto3" json:"role,omitempty"`
	Status        int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	Avatar        string                 `protobuf:"bytes,7,opt,name=avatar,proto3" json:"avatar,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserListItem) Reset() {
	*x = UserListItem{}
	mi := &file_services_rpc_auth_desc_auth_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserListItem) ProtoMessage() {}

func (x *UserListItem) ProtoReflect() protoreflect.Message {
	mi := &file_services_rpc_auth_desc_auth_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserListItem.ProtoReflect.Descriptor instead.
func (*UserListItem) Descriptor() ([]byte, []int) {
	return file_services_rpc_auth_desc_auth_proto_rawDescGZIP(), []int{19}
}

func (x *UserListItem) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserListItem) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserListItem) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserListItem) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UserListItem) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

func (x *UserListItem) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UserListItem) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UserListItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

// 用户列表响应
type ListUsersResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*UserListItem        `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResp) Reset() {
	*x = ListUsersResp{}
	mi := &file_services_rpc_auth_desc_auth_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResp) ProtoMessage() {}

func (x *ListUsersResp) ProtoReflect() protoreflect.Message {
	mi := &file_services_rpc_auth_desc_auth_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResp.ProtoReflect.Descriptor instead.
func (*ListUsersResp) Descriptor() ([]byte, []int) {
	return file_services_rpc_auth_desc_auth_proto_rawDescGZIP(), []int{20}
}

func (x *ListUsersResp) GetList() []*UserListItem {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListUsersResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListUsersResp) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListUsersResp) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 用户详情请求
type GetUserDetailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserDetailReq) Reset() {
	*x = GetUserDetailReq{}
	mi := &file_services_rpc_auth_desc_auth_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserDetailReq) ProtoMessage() {}

func (x *GetUserDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_services_rpc_auth_desc_auth_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserDetailReq.ProtoReflect.Descriptor instead.
func (*GetUserDetailReq) Descriptor() ([]byte, []int) {
	return file_services_rpc_auth_desc_auth_proto_rawDescGZIP(), []int{21}
}

func (x *GetUserDetailReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserDetailResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Role          int32                  `protobuf:"varint,5,opt,name=role,proto3" json:"role,omitempty"`
	Status        int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	Avatar        string                 `protobuf:"bytes,7,opt,name=avatar,proto3" json:"avatar,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserDetailResp) Reset() {
	*x = GetUserDetailResp{}
	mi := &file_services_rpc_auth_desc_auth_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserDetailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserDetailResp) ProtoMessage() {}

func (x *GetUserDetailResp) ProtoReflect() protoreflect.Message {
	mi := &file_services_rpc_auth_desc_auth_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserDetailResp.ProtoReflect.Descriptor instead.
func (*GetUserDetailResp) Descriptor() ([]byte, []int) {
	return file_services_rpc_auth_desc_auth_proto_rawDescGZIP(), []int{22}
}

func (x *GetUserDetailResp) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserDetailResp) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetUserDetailResp) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GetUserDetailResp) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *GetUserDetailResp) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

func (x *GetUserDetailResp) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetUserDetailResp) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *GetUserDetailResp) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GetUserDetailResp) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// 更新用户状态请求
type UpdateUserStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserStatusReq) Reset() {
	*x = UpdateUserStatusReq{}
	mi := &file_services_rpc_auth_desc_auth_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserStatusReq) ProtoMessage() {}

func (x *UpdateUserStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_services_rpc_auth_desc_auth_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserStatusReq.ProtoReflect.Descriptor instead.
func (*UpdateUserStatusReq) Descriptor() ([]byte, []int) {
	return file_services_rpc_auth_desc_auth_proto_rawDescGZIP(), []int{23}
}

func (x *UpdateUserStatusReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateUserStatusReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type UpdateUserStatusResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserStatusResp) Reset() {
	*x = UpdateUserStatusResp{}
	mi := &file_services_rpc_auth_desc_auth_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserStatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserStatusResp) ProtoMessage() {}

func (x *UpdateUserStatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_services_rpc_auth_desc_auth_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserStatusResp.ProtoReflect.Descriptor instead.
func (*UpdateUserStatusResp) Descriptor() ([]byte, []int) {
	return file_services_rpc_auth_desc_auth_proto_rawDescGZIP(), []int{24}
}

func (x *UpdateUserStatusResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 删除用户请求
type DeleteUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserReq) Reset() {
	*x = DeleteUserReq{}
	mi := &file_services_rpc_auth_desc_auth_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserReq) ProtoMessage() {}

func (x *DeleteUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_services_rpc_auth_desc_auth_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserReq.ProtoReflect.Descriptor instead.
func (*DeleteUserReq) Descriptor() ([]byte, []int) {
	return file_services_rpc_auth_desc_auth_proto_rawDescGZIP(), []int{25}
}

func (x *DeleteUserReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteUserResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserResp) Reset() {
	*x = DeleteUserResp{}
	mi := &file_services_rpc_auth_desc_auth_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserResp) ProtoMessage() {}

func (x *DeleteUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_services_rpc_auth_desc_auth_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserResp.ProtoReflect.Descriptor instead.
func (*DeleteUserResp) Descriptor() ([]byte, []int) {
	return file_services_rpc_auth_desc_auth_proto_rawDescGZIP(), []int{26}
}

func (x *DeleteUserResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_services_rpc_auth_desc_auth_proto protoreflect.FileDescriptor

const file_services_rpc_auth_desc_auth_proto_rawDesc = "" +
	"\n" +
	"!services/rpc/auth/desc/auth.proto\x12\x04auth\x1a\x1cgoogle/api/annotations.proto\"\xa2\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\x12\x14\n" +
	"\x05phone\x18\x05 \x01(\tR\x05phone\x12\x12\n" +
	"\x04role\x18\x06 \x01(\x05R\x04role\x12\x16\n" +
	"\x06status\x18\a \x01(\x05R\x06status\"J\n" +
	"\x10UsernameLoginReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"A\n" +
	"\rEmailLoginReq\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"N\n" +
	"\tLoginResp\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04role\x18\x03 \x01(\x05R\x04role\"t\n" +
	"\x10EmailRegisterReq\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x12\n" +
	"\x04code\x18\x04 \x01(\tR\x04code\"(\n" +
	"\fRegisterResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"(\n" +
	"\x10ValidateTokenReq\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"3\n" +
	"\x11ValidateTokenResp\x12\x1e\n" +
	"\x04user\x18\x01 \x01(\v2\n" +
	".auth.UserR\x04user\"#\n" +
	"\vSendCodeReq\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"(\n" +
	"\fSendCodeResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\":\n" +
	"\x0eLoginByCodeReq\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\"T\n" +
	"\x0fLoginByCodeResp\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x12\n" +
	"\x04role\x18\x03 \x01(\x05R\x04role\")\n" +
	"\x0eGetUserInfoReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x8a\x01\n" +
	"\x0fGetUserInfoResp\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\x12\x14\n" +
	"\x05phone\x18\x05 \x01(\tR\x05phone\",\n" +
	"\x11GetUserProfileReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xa5\x02\n" +
	"\x12GetUserProfileResp\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\treal_name\x18\x02 \x01(\tR\brealName\x12\x16\n" +
	"\x06school\x18\x03 \x01(\tR\x06school\x12\x14\n" +
	"\x05major\x18\x04 \x01(\tR\x05major\x12\x14\n" +
	"\x05grade\x18\x05 \x01(\tR\x05grade\x12\x16\n" +
	"\x06gender\x18\x06 \x01(\x05R\x06gender\x12#\n" +
	"\rexpected_city\x18\a \x01(\tR\fexpectedCity\x12+\n" +
	"\x11expected_position\x18\b \x01(\tR\x10expectedPosition\x12+\n" +
	"\x11self_introduction\x18\t \x01(\tR\x10selfIntroduction\"\xa7\x02\n" +
	"\x14UpdateUserProfileReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\treal_name\x18\x02 \x01(\tR\brealName\x12\x16\n" +
	"\x06school\x18\x03 \x01(\tR\x06school\x12\x14\n" +
	"\x05major\x18\x04 \x01(\tR\x05major\x12\x14\n" +
	"\x05grade\x18\x05 \x01(\tR\x05grade\x12\x16\n" +
	"\x06gender\x18\x06 \x01(\x05R\x06gender\x12#\n" +
	"\rexpected_city\x18\a \x01(\tR\fexpectedCity\x12+\n" +
	"\x11expected_position\x18\b \x01(\tR\x10expectedPosition\x12+\n" +
	"\x11self_introduction\x18\t \x01(\tR\x10selfIntroduction\"1\n" +
	"\x15UpdateUserProfileResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"k\n" +
	"\fListUsersReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\x12\x12\n" +
	"\x04role\x18\x04 \x01(\x05R\x04role\"\xd2\x01\n" +
	"\fUserListItem\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x12\n" +
	"\x04role\x18\x05 \x01(\x05R\x04role\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\x12\x16\n" +
	"\x06avatar\x18\a \x01(\tR\x06avatar\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\"~\n" +
	"\rListUsersResp\x12&\n" +
	"\x04list\x18\x01 \x03(\v2\x12.auth.UserListItemR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"+\n" +
	"\x10GetUserDetailReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xf6\x01\n" +
	"\x11GetUserDetailResp\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x12\n" +
	"\x04role\x18\x05 \x01(\x05R\x04role\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\x12\x16\n" +
	"\x06avatar\x18\a \x01(\tR\x06avatar\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt\"F\n" +
	"\x13UpdateUserStatusReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\"0\n" +
	"\x14UpdateUserStatusResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"(\n" +
	"\rDeleteUserReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"*\n" +
	"\x0eDeleteUserResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xb5\x04\n" +
	"\vAuthService\x12]\n" +
	"\rUsernameLogin\x12\x16.auth.UsernameLoginReq\x1a\x0f.auth.LoginResp\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/api/auth/login/username\x12T\n" +
	"\n" +
	"EmailLogin\x12\x13.auth.EmailLoginReq\x1a\x0f.auth.LoginResp\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/api/auth/login/email\x12`\n" +
	"\rEmailRegister\x12\x16.auth.EmailRegisterReq\x1a\x12.auth.RegisterResp\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/api/auth/register/email\x12_\n" +
	"\rValidateToken\x12\x16.auth.ValidateTokenReq\x1a\x17.auth.ValidateTokenResp\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/api/auth/validate\x12Q\n" +
	"\bSendCode\x12\x11.auth.SendCodeReq\x1a\x12.auth.SendCodeResp\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/auth/send_code\x12[\n" +
	"\vLoginByCode\x12\x14.auth.LoginByCodeReq\x1a\x15.auth.LoginByCodeResp\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/api/auth/login/code2\xaf\x05\n" +
	"\vUserService\x12R\n" +
	"\vGetUserInfo\x12\x14.auth.GetUserInfoReq\x1a\x15.auth.GetUserInfoResp\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/api/user/info\x12^\n" +
	"\x0eGetUserProfile\x12\x17.auth.GetUserProfileReq\x1a\x18.auth.GetUserProfileResp\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/api/user/profile\x12j\n" +
	"\x11UpdateUserProfile\x12\x1a.auth.UpdateUserProfileReq\x1a\x1b.auth.UpdateUserProfileResp\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/api/user/profile\x12N\n" +
	"\tListUsers\x12\x12.auth.ListUsersReq\x1a\x13.auth.ListUsersResp\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/api/admin/users\x12d\n" +
	"\rGetUserDetail\x12\x16.auth.GetUserDetailReq\x1a\x17.auth.GetUserDetailResp\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/api/admin/users/{user_id}\x12m\n" +
	"\x10UpdateUserStatus\x12\x19.auth.UpdateUserStatusReq\x1a\x1a.auth.UpdateUserStatusResp\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\x1a\x17/api/admin/users/status\x12[\n" +
	"\n" +
	"DeleteUser\x12\x13.auth.DeleteUserReq\x1a\x14.auth.DeleteUserResp\"\"\x82\xd3\xe4\x93\x02\x1c*\x1a/api/admin/users/{user_id}B\x06Z\x04./pbb\x06proto3"

var (
	file_services_rpc_auth_desc_auth_proto_rawDescOnce sync.Once
	file_services_rpc_auth_desc_auth_proto_rawDescData []byte
)

func file_services_rpc_auth_desc_auth_proto_rawDescGZIP() []byte {
	file_services_rpc_auth_desc_auth_proto_rawDescOnce.Do(func() {
		file_services_rpc_auth_desc_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_rpc_auth_desc_auth_proto_rawDesc), len(file_services_rpc_auth_desc_auth_proto_rawDesc)))
	})
	return file_services_rpc_auth_desc_auth_proto_rawDescData
}

var file_services_rpc_auth_desc_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_services_rpc_auth_desc_auth_proto_goTypes = []any{
	(*User)(nil),                  // 0: auth.User
	(*UsernameLoginReq)(nil),      // 1: auth.UsernameLoginReq
	(*EmailLoginReq)(nil),         // 2: auth.EmailLoginReq
	(*LoginResp)(nil),             // 3: auth.LoginResp
	(*EmailRegisterReq)(nil),      // 4: auth.EmailRegisterReq
	(*RegisterResp)(nil),          // 5: auth.RegisterResp
	(*ValidateTokenReq)(nil),      // 6: auth.ValidateTokenReq
	(*ValidateTokenResp)(nil),     // 7: auth.ValidateTokenResp
	(*SendCodeReq)(nil),           // 8: auth.SendCodeReq
	(*SendCodeResp)(nil),          // 9: auth.SendCodeResp
	(*LoginByCodeReq)(nil),        // 10: auth.LoginByCodeReq
	(*LoginByCodeResp)(nil),       // 11: auth.LoginByCodeResp
	(*GetUserInfoReq)(nil),        // 12: auth.GetUserInfoReq
	(*GetUserInfoResp)(nil),       // 13: auth.GetUserInfoResp
	(*GetUserProfileReq)(nil),     // 14: auth.GetUserProfileReq
	(*GetUserProfileResp)(nil),    // 15: auth.GetUserProfileResp
	(*UpdateUserProfileReq)(nil),  // 16: auth.UpdateUserProfileReq
	(*UpdateUserProfileResp)(nil), // 17: auth.UpdateUserProfileResp
	(*ListUsersReq)(nil),          // 18: auth.ListUsersReq
	(*UserListItem)(nil),          // 19: auth.UserListItem
	(*ListUsersResp)(nil),         // 20: auth.ListUsersResp
	(*GetUserDetailReq)(nil),      // 21: auth.GetUserDetailReq
	(*GetUserDetailResp)(nil),     // 22: auth.GetUserDetailResp
	(*UpdateUserStatusReq)(nil),   // 23: auth.UpdateUserStatusReq
	(*UpdateUserStatusResp)(nil),  // 24: auth.UpdateUserStatusResp
	(*DeleteUserReq)(nil),         // 25: auth.DeleteUserReq
	(*DeleteUserResp)(nil),        // 26: auth.DeleteUserResp
}
var file_services_rpc_auth_desc_auth_proto_depIdxs = []int32{
	0,  // 0: auth.ValidateTokenResp.user:type_name -> auth.User
	19, // 1: auth.ListUsersResp.list:type_name -> auth.UserListItem
	1,  // 2: auth.AuthService.UsernameLogin:input_type -> auth.UsernameLoginReq
	2,  // 3: auth.AuthService.EmailLogin:input_type -> auth.EmailLoginReq
	4,  // 4: auth.AuthService.EmailRegister:input_type -> auth.EmailRegisterReq
	6,  // 5: auth.AuthService.ValidateToken:input_type -> auth.ValidateTokenReq
	8,  // 6: auth.AuthService.SendCode:input_type -> auth.SendCodeReq
	10, // 7: auth.AuthService.LoginByCode:input_type -> auth.LoginByCodeReq
	12, // 8: auth.UserService.GetUserInfo:input_type -> auth.GetUserInfoReq
	14, // 9: auth.UserService.GetUserProfile:input_type -> auth.GetUserProfileReq
	16, // 10: auth.UserService.UpdateUserProfile:input_type -> auth.UpdateUserProfileReq
	18, // 11: auth.UserService.ListUsers:input_type -> auth.ListUsersReq
	21, // 12: auth.UserService.GetUserDetail:input_type -> auth.GetUserDetailReq
	23, // 13: auth.UserService.UpdateUserStatus:input_type -> auth.UpdateUserStatusReq
	25, // 14: auth.UserService.DeleteUser:input_type -> auth.DeleteUserReq
	3,  // 15: auth.AuthService.UsernameLogin:output_type -> auth.LoginResp
	3,  // 16: auth.AuthService.EmailLogin:output_type -> auth.LoginResp
	5,  // 17: auth.AuthService.EmailRegister:output_type -> auth.RegisterResp
	7,  // 18: auth.AuthService.ValidateToken:output_type -> auth.ValidateTokenResp
	9,  // 19: auth.AuthService.SendCode:output_type -> auth.SendCodeResp
	11, // 20: auth.AuthService.LoginByCode:output_type -> auth.LoginByCodeResp
	13, // 21: auth.UserService.GetUserInfo:output_type -> auth.GetUserInfoResp
	15, // 22: auth.UserService.GetUserProfile:output_type -> auth.GetUserProfileResp
	17, // 23: auth.UserService.UpdateUserProfile:output_type -> auth.UpdateUserProfileResp
	20, // 24: auth.UserService.ListUsers:output_type -> auth.ListUsersResp
	22, // 25: auth.UserService.GetUserDetail:output_type -> auth.GetUserDetailResp
	24, // 26: auth.UserService.UpdateUserStatus:output_type -> auth.UpdateUserStatusResp
	26, // 27: auth.UserService.DeleteUser:output_type -> auth.DeleteUserResp
	15, // [15:28] is the sub-list for method output_type
	2,  // [2:15] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_services_rpc_auth_desc_auth_proto_init() }
func file_services_rpc_auth_desc_auth_proto_init() {
	if File_services_rpc_auth_desc_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_rpc_auth_desc_auth_proto_rawDesc), len(file_services_rpc_auth_desc_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_services_rpc_auth_desc_auth_proto_goTypes,
		DependencyIndexes: file_services_rpc_auth_desc_auth_proto_depIdxs,
		MessageInfos:      file_services_rpc_auth_desc_auth_proto_msgTypes,
	}.Build()
	File_services_rpc_auth_desc_auth_proto = out.File
	file_services_rpc_auth_desc_auth_proto_goTypes = nil
	file_services_rpc_auth_desc_auth_proto_depIdxs = nil
}
