// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: auth.proto

package authservice

import (
	"context"

	"gomicrox/services/rpc/auth/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	DeleteUserReq         = pb.DeleteUserReq
	DeleteUserResp        = pb.DeleteUserResp
	EmailLoginReq         = pb.EmailLoginReq
	EmailRegisterReq      = pb.EmailRegisterReq
	GetUserDetailReq      = pb.GetUserDetailReq
	GetUserDetailResp     = pb.GetUserDetailResp
	GetUserInfoReq        = pb.GetUserInfoReq
	GetUserInfoResp       = pb.GetUserInfoResp
	GetUserProfileReq     = pb.GetUserProfileReq
	GetUserProfileResp    = pb.GetUserProfileResp
	ListUsersReq          = pb.ListUsersReq
	ListUsersResp         = pb.ListUsersResp
	LoginByCodeReq        = pb.LoginByCodeReq
	LoginByCodeResp       = pb.LoginByCodeResp
	LoginResp             = pb.LoginResp
	RegisterResp          = pb.RegisterResp
	SendCodeReq           = pb.SendCodeReq
	SendCodeResp          = pb.SendCodeResp
	UpdateUserProfileReq  = pb.UpdateUserProfileReq
	UpdateUserProfileResp = pb.UpdateUserProfileResp
	UpdateUserStatusReq   = pb.UpdateUserStatusReq
	UpdateUserStatusResp  = pb.UpdateUserStatusResp
	User                  = pb.User
	UserListItem          = pb.UserListItem
	UsernameLoginReq      = pb.UsernameLoginReq
	ValidateTokenReq      = pb.ValidateTokenReq
	ValidateTokenResp     = pb.ValidateTokenResp

	AuthService interface {
		UsernameLogin(ctx context.Context, in *UsernameLoginReq, opts ...grpc.CallOption) (*LoginResp, error)
		EmailLogin(ctx context.Context, in *EmailLoginReq, opts ...grpc.CallOption) (*LoginResp, error)
		EmailRegister(ctx context.Context, in *EmailRegisterReq, opts ...grpc.CallOption) (*RegisterResp, error)
		ValidateToken(ctx context.Context, in *ValidateTokenReq, opts ...grpc.CallOption) (*ValidateTokenResp, error)
		SendCode(ctx context.Context, in *SendCodeReq, opts ...grpc.CallOption) (*SendCodeResp, error)
		LoginByCode(ctx context.Context, in *LoginByCodeReq, opts ...grpc.CallOption) (*LoginByCodeResp, error)
	}

	defaultAuthService struct {
		cli zrpc.Client
	}
)

func NewAuthService(cli zrpc.Client) AuthService {
	return &defaultAuthService{
		cli: cli,
	}
}

func (m *defaultAuthService) UsernameLogin(ctx context.Context, in *UsernameLoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	client := pb.NewAuthServiceClient(m.cli.Conn())
	return client.UsernameLogin(ctx, in, opts...)
}

func (m *defaultAuthService) EmailLogin(ctx context.Context, in *EmailLoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	client := pb.NewAuthServiceClient(m.cli.Conn())
	return client.EmailLogin(ctx, in, opts...)
}

func (m *defaultAuthService) EmailRegister(ctx context.Context, in *EmailRegisterReq, opts ...grpc.CallOption) (*RegisterResp, error) {
	client := pb.NewAuthServiceClient(m.cli.Conn())
	return client.EmailRegister(ctx, in, opts...)
}

func (m *defaultAuthService) ValidateToken(ctx context.Context, in *ValidateTokenReq, opts ...grpc.CallOption) (*ValidateTokenResp, error) {
	client := pb.NewAuthServiceClient(m.cli.Conn())
	return client.ValidateToken(ctx, in, opts...)
}

func (m *defaultAuthService) SendCode(ctx context.Context, in *SendCodeReq, opts ...grpc.CallOption) (*SendCodeResp, error) {
	client := pb.NewAuthServiceClient(m.cli.Conn())
	return client.SendCode(ctx, in, opts...)
}

func (m *defaultAuthService) LoginByCode(ctx context.Context, in *LoginByCodeReq, opts ...grpc.CallOption) (*LoginByCodeResp, error) {
	client := pb.NewAuthServiceClient(m.cli.Conn())
	return client.LoginByCode(ctx, in, opts...)
}
