syntax = "proto3";

package upload;
option go_package = "./pb";

message UploadReq {
  bytes  file         = 1; // 文件二进制
  string fileName     = 2; // 原始文件名
  int64  fileSize     = 3; // 文件大小
  string fileType     = 4; // 文件类型(image/png)
  string uploadUserID = 5; // 上传者用户ID（权限控制核心）
}

message UploadResp{
  string msg      = 1;
  string filePath = 2; // OSS访问URL
  string fileName = 3;
  int64  fileSize = 4;
  string fileType = 5;
}

service Upload {
  rpc Upload(UploadReq) returns (UploadResp);
}